### ISSUE TITLE
建议显示设备序列号

### ISSUE THREAD

**Issue by kickTiger** [LapplandSP/QtAdb#3]
又一个小建议，在设备信息界面，能否增加显示设备序列号，

序列号这个是唯一值，方便多设备区分

**Comment by LapplandSP** [comment]
ADB获取IMEI需要手机已获取root权限，涉及su的操作近几个版本不会添加😂

**Comment by kickTiger** [comment]
> ADB获取IMEI需要手机已获取root权限，涉及su的操作近几个版本不会添加😂

可能是我描述的问题，是adb devices 显示的设备名称，这个不需要root权限，多设备的时候用这个指定设备。
在【设备信息】菜单中，也可以列出来方便复制和识别
