### ISSUE TITLE
scene5 的激活命令有所改变

### ISSUE THREAD

**Issue by gbxm** [LapplandSP/QtAdb#5]
目前软件内关于scene的激活命令为adb shell sh /data/user/0/com.omarea.vtools/files/up.sh
但是新版内发现激活命令为adb shell sh /sdcard/Android/data/com.omarea.vtools/up.sh
还请及时同步

**Comment by LapplandSP** [comment]
您好，已经收到反馈，目前开发环境受损，可能要比较久

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年11月29日 14:59
收件人: ***@***.***>
抄送: ***@***.***>
主题: [LapplandSP/QtAdb] scene5 的激活命令有所改变 (Issue #5)


目前软件内关于scene的激活命令为adb shell sh /data/user/0/com.omarea.vtools/files/up.sh
但是新版内发现激活命令为adb shell sh /sdcard/Android/data/com.omarea.vtools/up.sh
还请及时同步

―

**Comment by LapplandSP** [comment]
已更改
